import type { AuditEvent } from '@/lib/types'

export const AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'AUD-001',
    timestamp: '2024-06-13T10:30:00',
    user_name: 'Jane Karimi',
    user_role: 'Facility Manager',
    module: 'notices',
    action: 'sent',
    entity_type: 'Notice',
    entity_id: 'NTC-003',
    entity_label: 'Rent Increase — James Mwangi (A-101)',
    description: 'Notice NTC-003 (Rent Increase) sent to James Mwangi via email and hand delivery.',
    ip_address: '192.168.1.10',
  },
  {
    id: 'AUD-002',
    timestamp: '2024-06-13T09:45:00',
    user_name: 'Jane Karimi',
    user_role: 'Facility Manager',
    module: 'financials',
    action: 'created',
    entity_type: 'Charge',
    entity_id: 'CHG-089',
    entity_label: 'Rent — U-202 June 2024',
    description: 'Monthly rent charge KES 42,000 created for Block B – Unit 202 (June 2024).',
    ip_address: '192.168.1.10',
  },
  {
    id: 'AUD-003',
    timestamp: '2024-06-13T08:55:00',
    user_name: 'System',
    user_role: 'Automation',
    module: 'utilities',
    action: 'created',
    entity_type: 'MeterReading',
    entity_id: 'RDG-047',
    entity_label: 'Smart Read — MTR-004 (A-102)',
    description: 'Automated smart meter reading captured for MTR-004 (Block A – Unit 102 electricity).',
  },
  {
    id: 'AUD-004',
    timestamp: '2024-06-12T17:30:00',
    user_name: 'Jane Karimi',
    user_role: 'Facility Manager',
    module: 'people',
    action: 'updated',
    entity_type: 'Person',
    entity_id: 'P-006',
    entity_label: 'Samuel Kipchoge',
    description: 'Contact details updated for Samuel Kipchoge (Block B – Unit 201).',
    ip_address: '192.168.1.10',
    changes: [
      { field: 'phone', from: '+254 722 000 111', to: '+254 733 000 111' },
    ],
  },
  {
    id: 'AUD-005',
    timestamp: '2024-06-12T16:00:00',
    user_name: 'James Mwenye',
    user_role: 'Maintenance Supervisor',
    module: 'maintenance',
    action: 'updated',
    entity_type: 'WorkOrder',
    entity_id: 'WO-015',
    entity_label: 'Blocked Drain — C-302',
    description: 'Work order WO-015 status updated from open to in_progress. Assigned to Ahmed Suleiman.',
    ip_address: '192.168.1.22',
    changes: [
      { field: 'status', from: 'open', to: 'in_progress' },
      { field: 'assigned_to', from: '', to: 'Ahmed Suleiman' },
    ],
  },
  {
    id: 'AUD-006',
    timestamp: '2024-06-12T09:00:00',
    user_name: 'Admin',
    user_role: 'System Administrator',
    module: 'settings',
    action: 'updated',
    entity_type: 'Setting',
    entity_id: 'SET-late-fee',
    entity_label: 'Late Payment Penalty Rate',
    description: 'Late payment penalty rate updated from 1.5% per week to 2% per week.',
    ip_address: '192.168.1.5',
    changes: [
      { field: 'late_fee_pct_per_week', from: '1.5', to: '2.0' },
    ],
  },
  {
    id: 'AUD-007',
    timestamp: '2024-06-11T14:20:00',
    user_name: 'Jane Karimi',
    user_role: 'Facility Manager',
    module: 'leases',
    action: 'created',
    entity_type: 'Lease',
    entity_id: 'LSE-009',
    entity_label: 'Lease — Brian Ochieng (B-202)',
    description: 'New lease created for Brian Ochieng, Block B – Unit 202. Start: 1 July 2024.',
    ip_address: '192.168.1.10',
  },
  {
    id: 'AUD-008',
    timestamp: '2024-06-11T11:00:00',
    user_name: 'Jane Karimi',
    user_role: 'Facility Manager',
    module: 'rules',
    action: 'created',
    entity_type: 'BreachRecord',
    entity_id: 'BRCH-003',
    entity_label: 'Subletting Breach — C-305',
    description: 'Breach record created for unauthorised subletting in Block C – Unit 305.',
    ip_address: '192.168.1.10',
  },
  {
    id: 'AUD-009',
    timestamp: '2024-06-10T08:00:00',
    user_name: 'Jane Karimi',
    user_role: 'Facility Manager',
    module: 'notices',
    action: 'sent',
    entity_type: 'Notice',
    entity_id: 'NTC-004',
    entity_label: 'Water Interruption Notice',
    description: 'Mass notice NTC-004 (Water Interruption) broadcast to all residents via SMS and email.',
    ip_address: '192.168.1.10',
  },
  {
    id: 'AUD-010',
    timestamp: '2024-06-09T22:15:00',
    user_name: 'Admin',
    user_role: 'System Administrator',
    module: 'settings',
    action: 'login',
    entity_type: 'Session',
    entity_id: 'SES-2024-06-09',
    entity_label: 'Admin Login',
    description: 'Administrator login from IP 41.90.100.22 (external).',
    ip_address: '41.90.100.22',
  },
]
