import type { FacilityMessage } from '@/lib/types'

export const FACILITY_MESSAGES: FacilityMessage[] = [
  {
    id: 'MSG-001',
    subject: 'Planned Water Interruption — 15 June 2024',
    body: 'Dear Resident,\n\nPlease note that water supply will be interrupted on Saturday 15 June 2024 from 8 AM to 4 PM due to scheduled tank maintenance. Kindly store adequate water in advance.\n\nGreen Valley Estate Management',
    audience_type: 'all_residents',
    recipient_count: 42,
    channels: ['sms', 'email'],
    status: 'sent',
    created_by: 'Jane Karimi',
    created_at: '2024-06-10T07:30:00',
    sent_at: '2024-06-10T08:00:00',
    delivery_stats: { sent: 42, delivered: 41, read: 38, failed: 1 },
  },
  {
    id: 'MSG-002',
    subject: 'Community Meeting — Saturday 22 June',
    body: 'Dear Resident,\n\nYou are invited to our quarterly community meeting on Saturday 22 June 2024 at 10 AM in the meeting room (Ground Floor Block A).\n\nAgenda: Service charge review, compound lighting upgrade, AOB.\n\nKindly confirm your attendance by Friday 21 June.',
    audience_type: 'all_residents',
    recipient_count: 42,
    channels: ['email', 'in_app'],
    status: 'sent',
    created_by: 'Jane Karimi',
    created_at: '2024-06-11T09:00:00',
    sent_at: '2024-06-11T09:05:00',
    delivery_stats: { sent: 42, delivered: 42, read: 29, failed: 0 },
  },
  {
    id: 'MSG-003',
    subject: 'Block B Parking Enforcement Notice',
    body: 'Dear Block B Resident,\n\nPlease note that from 1 July 2024, vehicle clamping will be enforced for vehicles parked in undesignated bays. Ensure your vehicle sticker is clearly displayed.',
    audience_type: 'block',
    audience_filter: 'Block B',
    recipient_count: 14,
    channels: ['sms'],
    status: 'sent',
    created_by: 'Jane Karimi',
    created_at: '2024-06-09T14:00:00',
    sent_at: '2024-06-09T14:05:00',
    delivery_stats: { sent: 14, delivered: 14, failed: 0 },
  },
  {
    id: 'MSG-004',
    subject: 'Reminder: June Service Charge Due',
    body: 'Dear Resident,\n\nThis is a reminder that your June 2024 service charge is due by 30 June 2024. Please ensure timely payment to avoid penalties.\n\nThank you.',
    audience_type: 'all_residents',
    recipient_count: 42,
    channels: ['sms', 'email'],
    status: 'draft',
    created_by: 'Jane Karimi',
    created_at: '2024-06-13T09:00:00',
    delivery_stats: { sent: 0, delivered: 0, failed: 0 },
  },
  {
    id: 'MSG-005',
    subject: 'Staff Briefing: New Visitor Pre-Registration Process',
    body: 'Dear Team,\n\nEffective 15 June 2024, all visitors must be pre-registered in the system before arrival. Walk-in visitors will require host confirmation via phone.\n\nPlease review the updated gate procedures in the staff manual.',
    audience_type: 'staff_only',
    recipient_count: 6,
    channels: ['email', 'in_app'],
    status: 'sent',
    created_by: 'Jane Karimi',
    created_at: '2024-06-12T16:00:00',
    sent_at: '2024-06-12T16:05:00',
    delivery_stats: { sent: 6, delivered: 6, read: 5, failed: 0 },
  },
]
