import type { ConsumableType, ConsumableIssuance, ConsumableStock } from '@/lib/types'

// ── Consumable Types ───────────────────────────────────────────────────────

export const CONSUMABLE_TYPES: ConsumableType[] = [
  {
    id: 'CT-001',
    name: 'Garbage Bags',
    description: 'Black biodegradable garbage bags issued monthly to each residential unit',
    unit_of_issue: 'roll',
    quantity_per_unit: 10,
    quantity_per_issue: 1,
    issue_frequency: 'monthly',
    eligible_unit_types: ['residential', 'office'],
    requires_clearance: true,
    clearance_charge_types: ['service_charge'],
    active: true,
    notes: 'Clearance required: service charge must be paid before issuance.',
  },
  {
    id: 'CT-002',
    name: 'Recycling Bags',
    description: 'Blue recycling bags for dry waste separation',
    unit_of_issue: 'pack',
    quantity_per_unit: 5,
    quantity_per_issue: 1,
    issue_frequency: 'monthly',
    eligible_unit_types: ['residential', 'office', 'commercial'],
    requires_clearance: false,
    clearance_charge_types: [],
    active: true,
  },
  {
    id: 'CT-003',
    name: 'Pest Control Treatment',
    description: 'Quarterly pest control spray for each unit',
    unit_of_issue: 'treatment',
    quantity_per_unit: 1,
    quantity_per_issue: 1,
    issue_frequency: 'quarterly',
    eligible_unit_types: ['residential', 'office', 'commercial'],
    requires_clearance: true,
    clearance_charge_types: ['service_charge', 'rent'],
    active: true,
    notes: 'Both rent and service charge must be cleared for quarterly treatment.',
  },
  {
    id: 'CT-004',
    name: 'Common Area Cleaning Supply',
    description: 'Monthly cleaning supply allocation per floor (not per unit)',
    unit_of_issue: 'pack',
    quantity_per_unit: 1,
    quantity_per_issue: 1,
    issue_frequency: 'monthly',
    eligible_unit_types: ['residential'],
    requires_clearance: false,
    clearance_charge_types: [],
    active: false,
    notes: 'Discontinued — now handled by vendor contract.',
  },
]

// ── Issuances — June 2024 run ──────────────────────────────────────────────

export const CONSUMABLE_ISSUANCES: ConsumableIssuance[] = [
  // Garbage Bags — June 2024 run
  {
    id: 'CI-001',
    consumable_type_id: 'CT-001',
    consumable_name: 'Garbage Bags',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    person_id: 'P-001',
    person_name: 'James Mwangi',
    quantity_issued: 1,
    issued_date: '2024-06-03',
    billing_period: '2024-06',
    issued_by: 'Alice Omondi',
    status: 'issued',
  },
  {
    id: 'CI-002',
    consumable_type_id: 'CT-001',
    consumable_name: 'Garbage Bags',
    unit_id: 'U-102',
    unit_label: 'Block A – Unit 102',
    person_id: 'P-003',
    person_name: 'Grace Njoroge',
    quantity_issued: 1,
    issued_date: '2024-06-03',
    billing_period: '2024-06',
    issued_by: 'Alice Omondi',
    status: 'issued',
  },
  {
    id: 'CI-003',
    consumable_type_id: 'CT-001',
    consumable_name: 'Garbage Bags',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    person_id: 'P-006',
    person_name: 'Samuel Kipchoge',
    quantity_issued: 0,
    issued_date: '2024-06-03',
    billing_period: '2024-06',
    issued_by: 'Alice Omondi',
    status: 'withheld',
    withheld_reason: 'Service charge outstanding — KES 3,500 unpaid (due 2024-06-01)',
  },
  {
    id: 'CI-004',
    consumable_type_id: 'CT-001',
    consumable_name: 'Garbage Bags',
    unit_id: 'U-205',
    unit_label: 'Block B – Unit 205',
    person_id: 'P-008',
    person_name: 'Beatrice Achieng',
    quantity_issued: 1,
    issued_date: '2024-06-03',
    billing_period: '2024-06',
    issued_by: 'Alice Omondi',
    status: 'issued',
  },
  {
    id: 'CI-005',
    consumable_type_id: 'CT-001',
    consumable_name: 'Garbage Bags',
    unit_id: 'U-301',
    unit_label: 'Block C – Unit 301',
    person_id: 'P-009',
    person_name: 'David Otieno',
    quantity_issued: 1,
    issued_date: '2024-06-03',
    billing_period: '2024-06',
    issued_by: 'Alice Omondi',
    status: 'issued',
  },
  {
    id: 'CI-006',
    consumable_type_id: 'CT-001',
    consumable_name: 'Garbage Bags',
    unit_id: 'U-302',
    unit_label: 'Block C – Unit 302',
    person_id: 'P-010',
    person_name: 'Faith Wambui',
    quantity_issued: 0,
    issued_date: '2024-06-03',
    billing_period: '2024-06',
    issued_by: 'Alice Omondi',
    status: 'withheld',
    withheld_reason: 'Service charge outstanding — KES 3,500 unpaid (due 2024-06-01)',
  },
  // Pending — not yet processed this period
  {
    id: 'CI-007',
    consumable_type_id: 'CT-001',
    consumable_name: 'Garbage Bags',
    unit_id: 'U-103',
    unit_label: 'Block A – Unit 103',
    person_id: 'P-004',
    person_name: 'Brian Odhiambo',
    quantity_issued: 0,
    issued_date: '',
    billing_period: '2024-06',
    issued_by: '',
    status: 'pending',
  },

  // Recycling Bags — June 2024 run (no clearance required)
  {
    id: 'CI-008',
    consumable_type_id: 'CT-002',
    consumable_name: 'Recycling Bags',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    person_id: 'P-001',
    person_name: 'James Mwangi',
    quantity_issued: 1,
    issued_date: '2024-06-03',
    billing_period: '2024-06',
    issued_by: 'Alice Omondi',
    status: 'issued',
  },
  {
    id: 'CI-009',
    consumable_type_id: 'CT-002',
    consumable_name: 'Recycling Bags',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    person_id: 'P-006',
    person_name: 'Samuel Kipchoge',
    quantity_issued: 1,
    issued_date: '2024-06-03',
    billing_period: '2024-06',
    issued_by: 'Alice Omondi',
    status: 'issued',
    notes: 'Recycling bags issued even though garbage bags withheld — no clearance required.',
  },

  // Previous month (May 2024) — all issued for history
  {
    id: 'CI-010',
    consumable_type_id: 'CT-001',
    consumable_name: 'Garbage Bags',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    person_id: 'P-006',
    person_name: 'Samuel Kipchoge',
    quantity_issued: 1,
    issued_date: '2024-05-02',
    billing_period: '2024-05',
    issued_by: 'Alice Omondi',
    status: 'issued',
    notes: 'May charges were clear — bags issued without issue.',
  },
]

// ── Stock Levels ───────────────────────────────────────────────────────────

export const CONSUMABLE_STOCK: ConsumableStock[] = [
  {
    id: 'CS-001',
    consumable_type_id: 'CT-001',
    consumable_name: 'Garbage Bags',
    current_stock: 8,
    unit_of_issue: 'rolls',
    reorder_level: 15,
    last_restocked_date: '2024-05-28',
    last_restocked_quantity: 30,
    last_restocked_by: 'John Kamau',
    notes: 'Stock below reorder level — place order before end of month.',
  },
  {
    id: 'CS-002',
    consumable_type_id: 'CT-002',
    consumable_name: 'Recycling Bags',
    current_stock: 24,
    unit_of_issue: 'packs',
    reorder_level: 10,
    last_restocked_date: '2024-05-15',
    last_restocked_quantity: 40,
    last_restocked_by: 'John Kamau',
  },
  {
    id: 'CS-003',
    consumable_type_id: 'CT-003',
    consumable_name: 'Pest Control Treatment',
    current_stock: 0,
    unit_of_issue: 'treatments',
    reorder_level: 5,
    last_restocked_date: '2024-03-01',
    last_restocked_quantity: 12,
    last_restocked_by: 'John Kamau',
    notes: 'Next quarterly run due July 2024 — contact vendor to schedule.',
  },
]
