import type { FacilityDocument } from '@/lib/types'

export const DOCUMENTS: FacilityDocument[] = [
  {
    id: 'DOC-001',
    name: 'Lease Agreement — James Mwangi (A-101)',
    category: 'lease_agreement',
    entity_type: 'lease',
    entity_id: 'LSE-001',
    entity_label: 'LSE-001 — Block A Unit 101',
    file_type: 'pdf',
    file_size_kb: 340,
    upload_date: '2022-01-15',
    uploaded_by: 'Jane Karimi',
    description: 'Signed lease agreement for Unit 101 commencing January 2022.',
    status: 'active',
    tags: ['lease', 'signed'],
  },
  {
    id: 'DOC-002',
    name: 'Move-In Inspection Report — U-101',
    category: 'inspection_report',
    entity_type: 'unit',
    entity_id: 'U-101',
    entity_label: 'Block A – Unit 101',
    file_type: 'pdf',
    file_size_kb: 520,
    upload_date: '2022-01-15',
    uploaded_by: 'James Mwenye',
    status: 'active',
    tags: ['inspection', 'move_in'],
  },
  {
    id: 'DOC-003',
    name: 'National ID — Grace Njoroge',
    category: 'id_kyc',
    entity_type: 'person',
    entity_id: 'P-003',
    entity_label: 'Grace Njoroge',
    file_type: 'jpg',
    file_size_kb: 180,
    upload_date: '2021-03-01',
    uploaded_by: 'Jane Karimi',
    status: 'active',
    tags: ['kyc', 'id'],
  },
  {
    id: 'DOC-004',
    name: 'Buildings Insurance Certificate 2024',
    category: 'insurance',
    entity_type: 'general',
    file_type: 'pdf',
    file_size_kb: 890,
    upload_date: '2024-01-05',
    uploaded_by: 'Admin',
    expiry_date: '2025-01-04',
    expiry_alert_days: 30,
    description: 'Annual buildings and common areas insurance policy — Jubilee Insurance.',
    status: 'active',
    tags: ['insurance', 'compliance'],
  },
  {
    id: 'DOC-005',
    name: 'Elevator Inspection Certificate — June 2024',
    category: 'compliance_certificate',
    entity_type: 'general',
    file_type: 'pdf',
    file_size_kb: 210,
    upload_date: '2024-06-01',
    uploaded_by: 'James Mwenye',
    expiry_date: '2025-06-01',
    expiry_alert_days: 60,
    description: 'Annual elevator inspection certification by Kenya Bureau of Standards.',
    status: 'active',
    tags: ['lift', 'compliance', 'statutory'],
  },
  {
    id: 'DOC-006',
    name: 'Cleaning Services Contract — SwiftClean Ltd',
    category: 'vendor_contract',
    entity_type: 'vendor',
    entity_label: 'SwiftClean Ltd',
    file_type: 'pdf',
    file_size_kb: 450,
    upload_date: '2024-01-10',
    uploaded_by: 'Admin',
    expiry_date: '2025-01-09',
    expiry_alert_days: 30,
    description: 'Annual cleaning services contract — common areas and corridors.',
    status: 'active',
    tags: ['vendor', 'contract', 'cleaning'],
  },
  {
    id: 'DOC-007',
    name: 'Move-Out Inspection Report — U-205 (Beatrice Achieng)',
    category: 'inspection_report',
    entity_type: 'unit',
    entity_id: 'U-205',
    entity_label: 'Block B – Unit 205',
    file_type: 'pdf',
    file_size_kb: 680,
    upload_date: '2024-04-29',
    uploaded_by: 'James Mwenye',
    description: 'Move-out inspection with damage assessment for deposit deductions.',
    status: 'active',
    tags: ['inspection', 'move_out', 'deposit'],
  },
  {
    id: 'DOC-008',
    name: 'Q1 2024 Financial Statement',
    category: 'financial_statement',
    entity_type: 'general',
    file_type: 'pdf',
    file_size_kb: 320,
    upload_date: '2024-04-10',
    uploaded_by: 'Admin',
    description: 'Quarterly financial summary — January to March 2024.',
    status: 'active',
    tags: ['financial', 'quarterly'],
  },
]
