import type { Engagement } from '@/lib/types'

export const ENGAGEMENTS: Engagement[] = [
  // ── Formal Votes ──────────────────────────────────────────────────────────
  {
    id: 'ENG-001',
    type: 'vote',
    title: 'Approve Special Levy — Perimeter Wall Repair',
    description: 'A special levy of KES 15,000 per unit is proposed to fund emergency repair of the perimeter wall on the eastern boundary, damaged by the March 2026 floods.',
    resolution_text: 'RESOLVED: That a special levy of KES 15,000 per unit be approved and collected in two equal instalments of KES 7,500 in July and August 2026 for the purpose of repairing the eastern perimeter wall.',
    status: 'open',
    eligible: 'owners',
    vote_weight: 'by_share_percent',
    quorum_percent: 50,
    is_anonymous: false,
    options: [
      { id: 'OPT-001-Y', label: 'For — Approve the levy' },
      { id: 'OPT-001-N', label: 'Against — Do not approve' },
      { id: 'OPT-001-A', label: 'Abstain' },
    ],
    opens_at: '2026-06-10T08:00:00Z',
    closes_at: '2026-06-20T17:00:00Z',
    created_by: 'admin',
    created_at: '2026-06-08T10:00:00Z',
    total_eligible: 9,
    total_responses: 5,
    results: [
      { option_id: 'OPT-001-Y', label: 'For',     count: 3, percent: 60, weighted_percent: 65 },
      { option_id: 'OPT-001-N', label: 'Against',  count: 1, percent: 20, weighted_percent: 25 },
      { option_id: 'OPT-001-A', label: 'Abstain',  count: 1, percent: 20, weighted_percent: 10 },
    ],
  },
  {
    id: 'ENG-002',
    type: 'vote',
    title: 'Elect AGM Chairperson 2026',
    description: 'Homeowners elect a chairperson to preside over the 2026 Annual General Meeting scheduled for July 15.',
    status: 'closed',
    eligible: 'owners',
    vote_weight: 'equal',
    quorum_percent: 50,
    is_anonymous: false,
    options: [
      { id: 'OPT-002-A', label: 'Grace Njeri (P-01)'  },
      { id: 'OPT-002-B', label: 'Lucy Kariuki (P-06)' },
      { id: 'OPT-002-C', label: 'Tom Oduya (P-08)'    },
    ],
    opens_at: '2026-05-20T08:00:00Z',
    closes_at: '2026-05-27T17:00:00Z',
    created_by: 'admin',
    created_at: '2026-05-18T09:00:00Z',
    total_eligible: 9,
    total_responses: 8,
    passed: true,
    results: [
      { option_id: 'OPT-002-A', label: 'Grace Njeri',   count: 4, percent: 50 },
      { option_id: 'OPT-002-B', label: 'Lucy Kariuki',  count: 3, percent: 37.5 },
      { option_id: 'OPT-002-C', label: 'Tom Oduya',     count: 1, percent: 12.5 },
    ],
  },

  // ── Polls ─────────────────────────────────────────────────────────────────
  {
    id: 'ENG-003',
    type: 'poll',
    title: 'Preferred time for common area power washing',
    description: 'We schedule a monthly power wash of all common areas and corridors. When do you prefer this happens?',
    status: 'open',
    eligible: 'all_residents',
    is_anonymous: false,
    options: [
      { id: 'OPT-003-A', label: 'Saturday morning (7am–10am)' },
      { id: 'OPT-003-B', label: 'Sunday morning (7am–10am)'   },
      { id: 'OPT-003-C', label: 'Weekday early morning (5am–7am)' },
    ],
    opens_at: '2026-06-12T08:00:00Z',
    closes_at: '2026-06-17T17:00:00Z',
    created_by: 'admin',
    created_at: '2026-06-11T14:00:00Z',
    total_eligible: 13,
    total_responses: 7,
    results: [
      { option_id: 'OPT-003-A', label: 'Saturday morning',         count: 4, percent: 57 },
      { option_id: 'OPT-003-B', label: 'Sunday morning',           count: 2, percent: 29 },
      { option_id: 'OPT-003-C', label: 'Weekday early morning',    count: 1, percent: 14 },
    ],
  },
  {
    id: 'ENG-004',
    type: 'poll',
    title: 'Cleaning service preference — renewal time',
    description: 'CleanPro Services contract is up for renewal in December. Should we renew with them or invite competing bids?',
    status: 'draft',
    eligible: 'owners',
    is_anonymous: false,
    options: [
      { id: 'OPT-004-A', label: 'Renew with CleanPro (known quality)' },
      { id: 'OPT-004-B', label: 'Invite competing bids first'          },
      { id: 'OPT-004-C', label: 'No preference — management decides'   },
    ],
    opens_at: '2026-07-01T08:00:00Z',
    closes_at: '2026-07-07T17:00:00Z',
    created_by: 'admin',
    created_at: '2026-06-13T10:00:00Z',
    total_eligible: 9,
    total_responses: 0,
  },

  // ── Anonymous Feedback ────────────────────────────────────────────────────
  {
    id: 'ENG-005',
    type: 'feedback',
    title: 'How satisfied are you with security services?',
    description: 'Rate your satisfaction with the current security setup. Your response is completely anonymous — we cannot see who submitted what.',
    status: 'closed',
    eligible: 'all_residents',
    is_anonymous: true,
    options: [
      { id: 'OPT-005-1', label: '⭐ Very dissatisfied' },
      { id: 'OPT-005-2', label: '⭐⭐ Dissatisfied'    },
      { id: 'OPT-005-3', label: '⭐⭐⭐ Neutral'        },
      { id: 'OPT-005-4', label: '⭐⭐⭐⭐ Satisfied'    },
      { id: 'OPT-005-5', label: '⭐⭐⭐⭐⭐ Very satisfied' },
    ],
    opens_at: '2026-05-01T08:00:00Z',
    closes_at: '2026-05-15T17:00:00Z',
    created_by: 'admin',
    created_at: '2026-04-28T09:00:00Z',
    total_eligible: 13,
    total_responses: 11,
    results: [
      { option_id: 'OPT-005-1', label: 'Very dissatisfied', count: 0, percent: 0   },
      { option_id: 'OPT-005-2', label: 'Dissatisfied',      count: 1, percent: 9   },
      { option_id: 'OPT-005-3', label: 'Neutral',           count: 2, percent: 18  },
      { option_id: 'OPT-005-4', label: 'Satisfied',         count: 5, percent: 45  },
      { option_id: 'OPT-005-5', label: 'Very satisfied',    count: 3, percent: 27  },
    ],
  },
  {
    id: 'ENG-006',
    type: 'feedback',
    title: 'Open feedback — what can we improve?',
    description: 'Share any concerns, suggestions, or compliments. No options — just write freely. 100% anonymous.',
    status: 'open',
    eligible: 'all_residents',
    is_anonymous: true,
    opens_at: '2026-06-01T08:00:00Z',
    closes_at: '2026-06-30T17:00:00Z',
    created_by: 'admin',
    created_at: '2026-05-30T14:00:00Z',
    total_eligible: 13,
    total_responses: 4,
  },
]
