import type { LeaseApplication, OnboardingApplication } from '@/lib/types'

export const LEASE_APPLICATIONS: LeaseApplication[] = [
  {
    id: 'APP-001',
    unit_id: 'U-304',
    unit_label: 'Block C – Unit 304',
    applicant_name: 'Faith Wanjiku',
    applicant_email: 'faith.wanjiku@email.com',
    applicant_phone: '+254 722 111 222',
    national_id: '34521876',
    employer: 'Kenya Commercial Bank',
    monthly_income: 95000,
    submitted_date: '2024-05-28',
    status: 'under_review',
    notes: 'Self-employed, provided bank statements for 6 months.',
  },
  {
    id: 'APP-002',
    unit_id: 'U-202',
    unit_label: 'Block B – Unit 202',
    applicant_name: 'Brian Ochieng',
    applicant_email: 'brian.ochieng@email.com',
    applicant_phone: '+254 733 444 555',
    national_id: '29876543',
    employer: 'Safaricom PLC',
    monthly_income: 120000,
    submitted_date: '2024-06-01',
    status: 'approved',
    reviewed_by: 'Jane Karimi',
    review_date: '2024-06-04',
    notes: 'Strong application. References checked.',
  },
  {
    id: 'APP-003',
    unit_id: 'U-105',
    unit_label: 'Block A – Unit 105',
    applicant_name: 'Amina Hassan',
    applicant_email: 'amina.hassan@email.com',
    applicant_phone: '+254 711 999 888',
    national_id: '38112233',
    employer: 'UNICEF Kenya',
    monthly_income: 180000,
    submitted_date: '2024-06-05',
    status: 'submitted',
  },
  {
    id: 'APP-004',
    unit_id: 'U-103',
    unit_label: 'Block A – Unit 103',
    applicant_name: 'Peter Kamau',
    applicant_email: 'peter.kamau@email.com',
    applicant_phone: '+254 700 123 456',
    national_id: '25443322',
    employer: 'Freelance Consultant',
    monthly_income: 60000,
    submitted_date: '2024-04-10',
    status: 'rejected',
    reviewed_by: 'Jane Karimi',
    review_date: '2024-04-15',
    rejection_reason: 'Income below minimum threshold. Monthly income does not meet 3x rent requirement.',
  },
]

export const ONBOARDING_APPLICATIONS: OnboardingApplication[] = [
  {
    id: 'ONB-001',
    unit_id: 'U-202',
    unit_label: 'Block B – Unit 202',
    applicant_name: 'Brian Ochieng',
    applicant_email: 'brian.ochieng@email.com',
    applicant_phone: '+254 733 444 555',
    national_id: '29876543',
    current_stage: 'deposit_payment',
    status: 'in_progress',
    submitted_date: '2024-06-01',
    target_move_in: '2024-07-01',
    assigned_to: 'Jane Karimi',
    stage_history: [
      { stage: 'applied',       completed_at: '2024-06-01', completed_by: 'System' },
      { stage: 'under_review',  completed_at: '2024-06-02', completed_by: 'Jane Karimi' },
      { stage: 'approved',      completed_at: '2024-06-04', completed_by: 'Jane Karimi', notes: 'All docs verified' },
      { stage: 'lease_signing', completed_at: '2024-06-07', completed_by: 'Jane Karimi', notes: 'Lease signed digitally' },
      { stage: 'deposit_payment' },
    ],
  },
  {
    id: 'ONB-002',
    unit_id: 'U-304',
    unit_label: 'Block C – Unit 304',
    applicant_name: 'Faith Wanjiku',
    applicant_email: 'faith.wanjiku@email.com',
    applicant_phone: '+254 722 111 222',
    national_id: '34521876',
    current_stage: 'under_review',
    status: 'in_progress',
    submitted_date: '2024-05-28',
    target_move_in: '2024-07-15',
    assigned_to: 'Jane Karimi',
    stage_history: [
      { stage: 'applied',      completed_at: '2024-05-28', completed_by: 'System' },
      { stage: 'under_review' },
    ],
  },
  {
    id: 'ONB-003',
    unit_id: 'U-401',
    unit_label: 'Block D – Unit 401',
    applicant_name: 'Michael Njeru',
    applicant_email: 'michael.njeru@email.com',
    applicant_phone: '+254 722 555 333',
    national_id: '31445566',
    current_stage: 'active',
    status: 'completed',
    submitted_date: '2024-04-01',
    target_move_in: '2024-05-01',
    lease_id: 'LSE-007',
    assigned_to: 'Jane Karimi',
    stage_history: [
      { stage: 'applied',            completed_at: '2024-04-01', completed_by: 'System' },
      { stage: 'under_review',       completed_at: '2024-04-03', completed_by: 'Jane Karimi' },
      { stage: 'approved',           completed_at: '2024-04-05', completed_by: 'Jane Karimi' },
      { stage: 'lease_signing',      completed_at: '2024-04-10', completed_by: 'Jane Karimi' },
      { stage: 'deposit_payment',    completed_at: '2024-04-12', completed_by: 'Jane Karimi', notes: 'KES 40,000 received' },
      { stage: 'move_in_inspection', completed_at: '2024-04-28', completed_by: 'James Mwenye', notes: 'Unit in good condition' },
      { stage: 'key_handover',       completed_at: '2024-04-30', completed_by: 'Jane Karimi' },
      { stage: 'active',             completed_at: '2024-05-01', completed_by: 'System' },
    ],
  },
]
