import type { Meter, MeterReading, MeterTypeHistory } from '@/lib/types'

export const METERS: Meter[] = [
  // ── Water meters ──────────────────────────────────────────────────────────
  {
    id: 'MTR-001',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    utility_type: 'water',
    meter_type: 'postpaid',
    meter_number: 'W-A101-01',
    account_number: 'ACC-W-0101',
    installation_date: '2020-01-15',
    status: 'active',
    current_billing_person: { person_id: 'P-001', name: 'James Mwangi' },
    billing_arrangement: 'billed_to_occupant',
    management_fee_pct: 5,
    last_reading: 4820,
    last_reading_date: '2024-05-31',
  },
  {
    id: 'MTR-002',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    utility_type: 'electricity',
    meter_type: 'prepaid',
    meter_number: 'E-A101-01',
    account_number: 'ACC-E-0101',
    installation_date: '2020-01-15',
    status: 'active',
    current_billing_person: { person_id: 'P-001', name: 'James Mwangi' },
    billing_arrangement: 'billed_to_occupant',
    last_reading: 12450,
    last_reading_date: '2024-05-28',
  },
  {
    id: 'MTR-003',
    unit_id: 'U-102',
    unit_label: 'Block A – Unit 102',
    utility_type: 'water_sewer',
    meter_type: 'postpaid',
    meter_number: 'WS-A102-01',
    account_number: 'ACC-WS-0102',
    installation_date: '2020-02-01',
    status: 'active',
    current_billing_person: { person_id: 'P-003', name: 'Grace Njoroge' },
    billing_arrangement: 'billed_to_occupant',
    management_fee_pct: 5,
    last_reading: 3210,
    last_reading_date: '2024-05-31',
  },
  {
    id: 'MTR-004',
    unit_id: 'U-102',
    unit_label: 'Block A – Unit 102',
    utility_type: 'electricity',
    meter_type: 'smart',
    meter_number: 'E-A102-SM-01',
    account_number: 'ACC-E-0102',
    installation_date: '2022-06-01',
    status: 'active',
    current_billing_person: { person_id: 'P-003', name: 'Grace Njoroge' },
    billing_arrangement: 'billed_to_occupant',
    last_reading: 8732,
    last_reading_date: '2024-06-01',
  },
  {
    id: 'MTR-005',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    utility_type: 'water',
    meter_type: 'postpaid',
    meter_number: 'W-B201-01',
    account_number: 'ACC-W-0201',
    installation_date: '2020-03-10',
    status: 'active',
    current_billing_person: { person_id: 'P-006', name: 'Samuel Kipchoge' },
    billing_arrangement: 'billed_to_occupant',
    management_fee_pct: 5,
    last_reading: 6100,
    last_reading_date: '2024-05-31',
  },
  {
    id: 'MTR-006',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    utility_type: 'electricity',
    meter_type: 'postpaid',
    meter_number: 'E-B201-01',
    account_number: 'ACC-E-0201',
    installation_date: '2020-03-10',
    status: 'active',
    current_billing_person: { person_id: 'P-006', name: 'Samuel Kipchoge' },
    billing_arrangement: 'billed_to_occupant',
    last_reading: 9820,
    last_reading_date: '2024-05-31',
  },
  {
    id: 'MTR-007',
    unit_id: 'U-205',
    unit_label: 'Block B – Unit 205',
    utility_type: 'water',
    meter_type: 'smart',
    meter_number: 'W-B205-SM-01',
    account_number: 'ACC-W-0205',
    installation_date: '2023-01-01',
    status: 'active',
    current_billing_person: { person_id: 'P-008', name: 'Beatrice Achieng' },
    billing_arrangement: 'billed_to_occupant',
    management_fee_pct: 5,
    last_reading: 1580,
    last_reading_date: '2024-06-01',
  },
  {
    id: 'MTR-008',
    unit_id: 'S-01',
    unit_label: 'Shop S-01 (Ground Floor)',
    utility_type: 'electricity',
    meter_type: 'postpaid',
    meter_number: 'E-S01-01',
    account_number: 'ACC-E-S01',
    installation_date: '2021-04-01',
    status: 'active',
    current_billing_person: { person_id: 'P-012', name: 'Makena Chege' },
    billing_arrangement: 'billed_to_occupant',
    last_reading: 22100,
    last_reading_date: '2024-05-31',
  },
  {
    id: 'MTR-009',
    unit_id: 'U-301',
    unit_label: 'Block C – Unit 301',
    utility_type: 'internet',
    meter_type: 'postpaid',
    meter_number: 'INT-C301-01',
    account_number: 'ACC-INT-0301',
    installation_date: '2022-09-01',
    status: 'active',
    current_billing_person: { person_id: 'P-009', name: 'David Otieno' },
    billing_arrangement: 'billed_to_occupant',
    last_reading: 0,
    last_reading_date: '2024-06-01',
  },
  {
    id: 'MTR-010',
    unit_id: 'U-103',
    unit_label: 'Block A – Unit 103',
    utility_type: 'water',
    meter_type: 'postpaid',
    meter_number: 'W-A103-01',
    account_number: 'ACC-W-0103',
    installation_date: '2020-01-15',
    status: 'inactive',
    billing_arrangement: 'billed_to_unit',
    last_reading: 2890,
    last_reading_date: '2024-04-30',
  },

  // ── Water supply chain meters ─────────────────────────────────────────────
  // These meters are NOT linked to individual units — they sit at the
  // supplier / tank / distribution level of the water supply chain.

  // Supplier meters — measure inflow from each source
  {
    id: 'MTR-S01',
    unit_label: 'NCWSC Municipal Supply',
    utility_type: 'water' as const,
    meter_type: 'smart' as const,
    meter_number: 'W-SUP-NCWSC-01',
    account_number: 'ACC-NCWSC-001',
    installation_date: '2021-06-01',
    status: 'active' as const,
    billing_arrangement: 'management_bill' as const,
    meter_role: 'supplier' as const,
    supplier_id: 'WS-001',
    tank_id: 'TK-001',
    last_reading: 84320,
    last_reading_date: '2024-06-30',
  },
  {
    id: 'MTR-S02',
    unit_label: 'Estate Borehole',
    utility_type: 'water' as const,
    meter_type: 'postpaid' as const,
    meter_number: 'W-SUP-BH-01',
    account_number: 'ACC-BH-001',
    installation_date: '2021-09-15',
    status: 'active' as const,
    billing_arrangement: 'management_bill' as const,
    meter_role: 'supplier' as const,
    supplier_id: 'WS-002',
    tank_id: 'TK-001',
    last_reading: 18940,
    last_reading_date: '2024-06-30',
  },

  // Tank outflow meter — measures total water leaving the reserve tank
  {
    id: 'MTR-T01',
    unit_label: 'Main Tank — Outflow',
    utility_type: 'water' as const,
    meter_type: 'smart' as const,
    meter_number: 'W-TANK-OUT-01',
    account_number: 'ACC-TANK-OUT-001',
    installation_date: '2021-06-01',
    status: 'active' as const,
    billing_arrangement: 'management_bill' as const,
    meter_role: 'tank_outflow' as const,
    tank_id: 'TK-001',
    last_reading: 102140,
    last_reading_date: '2024-06-30',
  },

  // Distribution zone meters — one per zone, between tank outflow and unit meters
  {
    id: 'MTR-D01',
    unit_label: 'Zone: Block A',
    utility_type: 'water' as const,
    meter_type: 'smart' as const,
    meter_number: 'W-DIST-A-01',
    account_number: 'ACC-DIST-A-001',
    installation_date: '2021-06-01',
    status: 'active' as const,
    billing_arrangement: 'management_bill' as const,
    meter_role: 'distribution' as const,
    tank_id: 'TK-001',
    zone_id: 'WZ-A',
    last_reading: 44810,
    last_reading_date: '2024-06-30',
  },
  {
    id: 'MTR-D02',
    unit_label: 'Zone: Block B & C',
    utility_type: 'water' as const,
    meter_type: 'smart' as const,
    meter_number: 'W-DIST-BC-01',
    account_number: 'ACC-DIST-BC-001',
    installation_date: '2021-06-01',
    status: 'active' as const,
    billing_arrangement: 'management_bill' as const,
    meter_role: 'distribution' as const,
    tank_id: 'TK-001',
    zone_id: 'WZ-BC',
    last_reading: 57330,
    last_reading_date: '2024-06-30',
  },
]

export const METER_READINGS: MeterReading[] = [
  {
    id: 'RDG-001',
    meter_id: 'MTR-001',
    unit_label: 'Block A – Unit 101',
    utility_type: 'water',
    meter_number: 'W-A101-01',
    previous_value: 4710,
    current_value: 4820,
    units_consumed: 110,
    reading_date: '2024-05-31',
    billing_period: '2024-05',
    source: 'manual',
    read_by: 'John Kamau',
    unit_cost: 80,
    amount_due: 8800,
    management_fee: 440,
    status: 'billed',
  },
  {
    id: 'RDG-002',
    meter_id: 'MTR-001',
    unit_label: 'Block A – Unit 101',
    utility_type: 'water',
    meter_number: 'W-A101-01',
    previous_value: 4610,
    current_value: 4710,
    units_consumed: 100,
    reading_date: '2024-04-30',
    billing_period: '2024-04',
    source: 'manual',
    read_by: 'John Kamau',
    unit_cost: 80,
    amount_due: 8000,
    management_fee: 400,
    status: 'billed',
  },
  {
    id: 'RDG-003',
    meter_id: 'MTR-003',
    unit_label: 'Block A – Unit 102',
    utility_type: 'water_sewer',
    meter_number: 'WS-A102-01',
    previous_value: 3100,
    current_value: 3210,
    units_consumed: 110,
    reading_date: '2024-05-31',
    billing_period: '2024-05',
    source: 'manual',
    read_by: 'John Kamau',
    unit_cost: 95,
    amount_due: 10450,
    management_fee: 522,
    status: 'billed',
  },
  {
    id: 'RDG-004',
    meter_id: 'MTR-004',
    unit_label: 'Block A – Unit 102',
    utility_type: 'electricity',
    meter_number: 'E-A102-SM-01',
    previous_value: 8650,
    current_value: 8732,
    units_consumed: 82,
    reading_date: '2024-06-01',
    billing_period: '2024-05',
    source: 'smart_iot',
    read_by: 'system',
    unit_cost: 25,
    amount_due: 2050,
    status: 'pending_bill',
  },
  {
    id: 'RDG-005',
    meter_id: 'MTR-005',
    unit_label: 'Block B – Unit 201',
    utility_type: 'water',
    meter_number: 'W-B201-01',
    previous_value: 5980,
    current_value: 6100,
    units_consumed: 120,
    reading_date: '2024-05-31',
    billing_period: '2024-05',
    source: 'manual',
    read_by: 'John Kamau',
    unit_cost: 80,
    amount_due: 9600,
    management_fee: 480,
    status: 'billed',
  },
  {
    id: 'RDG-006',
    meter_id: 'MTR-006',
    unit_label: 'Block B – Unit 201',
    utility_type: 'electricity',
    meter_number: 'E-B201-01',
    previous_value: 9690,
    current_value: 9820,
    units_consumed: 130,
    reading_date: '2024-05-31',
    billing_period: '2024-05',
    source: 'manual',
    read_by: 'John Kamau',
    unit_cost: 25,
    amount_due: 3250,
    status: 'billed',
  },
]

export const METER_TYPE_HISTORY: MeterTypeHistory[] = [
  {
    id: 'HIST-001',
    meter_id: 'MTR-004',
    unit_label: 'Block A – Unit 102',
    from_type: 'postpaid',
    to_type: 'smart',
    migration_date: '2022-06-01',
    final_reading: 5210,
    migrated_by: 'John Kamau',
    notes: 'Upgraded to smart meter under Phase 2 IoT rollout. Final postpaid reading taken and verified.',
  },
  {
    id: 'HIST-002',
    meter_id: 'MTR-007',
    unit_label: 'Block B – Unit 205',
    from_type: 'postpaid',
    to_type: 'smart',
    migration_date: '2023-01-01',
    final_reading: 980,
    migrated_by: 'John Kamau',
    notes: 'Phase 3 smart meter rollout — Block B.',
  },
]

// ── Inventory meters (unassigned) ─────────────────────────────────────────
import type { MeterExtended } from '@/lib/types'

export const INVENTORY_METERS: MeterExtended[] = [
  {
    id: 'INV-001',
    category: 'water',
    meter_subtype: 'unit_sub',
    billing_mode: 'postpaid',
    serial_number: 'ITRON-WM-2024-0041',
    make: 'Itron',
    model: 'Actaris SL7000',
    meter_number: 'WM-0041',
    unit_of_measure: 'm³',
    water_specs: { pipe_diameter_mm: 15, meter_class: 'C', connection_type: 'inline' },
    opening_reading: 0,
    opening_reading_date: '2026-06-13',
    rate_per_unit: 85,
    billing_cycle: 'monthly',
    auto_generate_charges: true,
    status: 'inventory',
    created_at: '2026-06-13T09:00:00Z',
    notes: 'Purchased for Block C expansion',
  },
  {
    id: 'INV-002',
    category: 'water',
    meter_subtype: 'unit_sub',
    billing_mode: 'postpaid',
    serial_number: 'ITRON-WM-2024-0042',
    make: 'Itron',
    model: 'Actaris SL7000',
    meter_number: 'WM-0042',
    unit_of_measure: 'm³',
    water_specs: { pipe_diameter_mm: 15, meter_class: 'C', connection_type: 'inline' },
    opening_reading: 0,
    opening_reading_date: '2026-06-13',
    rate_per_unit: 85,
    billing_cycle: 'monthly',
    auto_generate_charges: true,
    status: 'inventory',
    created_at: '2026-06-13T09:00:00Z',
    notes: 'Purchased for Block C expansion',
  },
  {
    id: 'INV-003',
    category: 'electricity',
    meter_subtype: 'unit_sub',
    billing_mode: 'prepaid',
    serial_number: 'KPLC-LUKU-2025-8812',
    make: 'Landis+Gyr',
    model: 'E110',
    meter_number: 'LUKU-8812',
    token_number: '34522-88120-44',
    utility_account_number: 'KPLC-ACC-8812',
    unit_of_measure: 'kWh',
    electricity_specs: { phase: 'single', voltage_rating: '240V' },
    opening_reading: 0,
    opening_reading_date: '2026-05-20',
    rate_per_unit: 25.50,
    billing_cycle: 'monthly',
    auto_generate_charges: false,
    status: 'inventory',
    created_at: '2026-05-20T08:00:00Z',
    notes: 'KPLC prepaid — top-up tracking only, charges billed direct',
  },
  {
    id: 'INV-004',
    category: 'electricity',
    meter_subtype: 'common_area',
    billing_mode: 'postpaid',
    serial_number: 'LGY-CA-2025-0019',
    make: 'Landis+Gyr',
    model: 'E450',
    meter_number: 'CA-0019',
    utility_account_number: 'KPLC-ACC-CA-019',
    unit_of_measure: 'kWh',
    electricity_specs: { phase: 'three', voltage_rating: '415V', max_demand_kva: 50 },
    opening_reading: 0,
    opening_reading_date: '2026-06-01',
    rate_per_unit: 22.00,
    billing_cycle: 'monthly',
    auto_generate_charges: true,
    status: 'inventory',
    created_at: '2026-06-01T00:00:00Z',
    notes: 'Earmarked for new gym / common area — awaiting wiring completion',
  },
  {
    id: 'INV-005',
    category: 'gas',
    meter_subtype: 'unit_sub',
    billing_mode: 'prepaid',
    serial_number: 'ELSTER-G4-2025-0331',
    make: 'Elster',
    model: 'BK-G4',
    meter_number: 'G4-0331',
    unit_of_measure: 'm³',
    gas_specs: { gas_type: 'natural_gas', capacity_m3_per_hr: 6, working_pressure_mbar: 21 },
    opening_reading: 0,
    opening_reading_date: '2026-06-10',
    rate_per_unit: 120,
    billing_cycle: 'monthly',
    auto_generate_charges: false,
    calibration: {
      cert_number: 'KEBS-GAS-2025-0331',
      calibration_date: '2025-03-15',
      expiry_date: '2027-03-14',
      calibrated_by: 'KEBS Nairobi Laboratory',
      document_uploaded: true,
    },
    status: 'inventory',
    created_at: '2026-06-10T00:00:00Z',
  },
]
