import type { AlertNotification } from '@/lib/types'

export const ALERT_NOTIFICATIONS: AlertNotification[] = [
  {
    id: 'alert_001',
    category: 'payment_overdue',
    severity: 'critical',
    title: 'Rent overdue — A-302',
    body: 'Rose Akinyi (A-302) has an outstanding rent of KES 65,000 — 45 days overdue.',
    link_href: '/financials',
    link_label: 'View Charges',
    created_at: '2026-06-10T08:00:00Z',
    read: false,
    unit_id: 'U-302',
    unit_label: 'A-302',
  },
  {
    id: 'alert_002',
    category: 'lease_expiry',
    severity: 'warning',
    title: 'Lease expiring in 18 days — A-102',
    body: "Sarah Otieno's lease (A-102) expires on 2026-06-30. Renewal not yet initiated.",
    link_href: '/leases',
    link_label: 'View Lease',
    created_at: '2026-06-12T09:00:00Z',
    read: false,
    unit_id: 'U-102',
    unit_label: 'A-102',
  },
  {
    id: 'alert_003',
    category: 'disconnection_due',
    severity: 'warning',
    title: 'Disconnection notice due — MTR-001',
    body: 'Water meter W-A101-01 (A-101, James Mwangi) unpaid for 14 days. Formal disconnection notice should be sent.',
    link_href: '/utilities',
    link_label: 'View Meters',
    created_at: '2026-06-13T07:30:00Z',
    read: false,
    unit_id: 'U-101',
    unit_label: 'A-101',
  },
  {
    id: 'alert_004',
    category: 'maintenance_overdue',
    severity: 'warning',
    title: '3 work orders open > 7 days',
    body: 'Plumbing (A-201), electrical fault (B-03), and roof inspection (Block C) have had no update in over a week.',
    link_href: '/maintenance',
    link_label: 'View Work Orders',
    created_at: '2026-06-11T10:00:00Z',
    read: false,
  },
  {
    id: 'alert_005',
    category: 'low_stock',
    severity: 'info',
    title: 'Low stock — Chlorine tablets',
    body: 'Chlorine tablets stock is at 2 units — below the minimum threshold of 5.',
    link_href: '/consumables',
    link_label: 'View Stock',
    created_at: '2026-06-12T14:00:00Z',
    read: false,
  },
  {
    id: 'alert_006',
    category: 'water_loss',
    severity: 'critical',
    title: 'Water loss 38% — Block A zone',
    body: 'Block A zone meter shows 38% unaccounted water loss this month. Investigate for leaks.',
    link_href: '/utilities',
    link_label: 'View Water Balance',
    created_at: '2026-06-13T06:00:00Z',
    read: false,
  },
  {
    id: 'alert_007',
    category: 'document_expiry',
    severity: 'warning',
    title: 'Insurance certificate expires in 22 days',
    body: "Property insurance certificate expires on 2026-07-05. Upload renewal before it lapses.",
    link_href: '/documents',
    link_label: 'View Documents',
    created_at: '2026-06-11T08:00:00Z',
    read: true,
  },
  {
    id: 'alert_008',
    category: 'lease_expiry',
    severity: 'info',
    title: 'Lease expiring in 28 days — A-201',
    body: "Peter Ochieng's lease (A-201) expires on 2026-07-10. Consider sending a renewal notice.",
    link_href: '/leases',
    link_label: 'View Lease',
    created_at: '2026-06-13T09:00:00Z',
    read: true,
    unit_id: 'U-201',
    unit_label: 'A-201',
  },
]
