import type { Notice, NoticeTemplate } from '@/lib/types'

export const NOTICE_TEMPLATES: NoticeTemplate[] = [
  {
    id: 'TPL-001',
    name: 'Rent Arrears Demand',
    notice_type: 'arrears_demand',
    subject: 'NOTICE OF RENT ARREARS — {{unit_label}}',
    body: 'Dear {{tenant_name}},\n\nThis notice serves as a formal demand for payment of outstanding rent arrears of KES {{amount_due}} for the period {{period}}.\n\nPayment is required within 7 days of this notice. Failure to settle will result in escalation as per your tenancy agreement.\n\nKindly contact management immediately to make arrangements.\n\nYours faithfully,\nGreen Valley Estate Management',
    variables: ['tenant_name', 'unit_label', 'amount_due', 'period'],
    active: true,
  },
  {
    id: 'TPL-002',
    name: 'Notice to Vacate',
    notice_type: 'notice_to_vacate',
    subject: 'NOTICE TO VACATE — {{unit_label}}',
    body: 'Dear {{tenant_name}},\n\nThis is formal notice that your tenancy for {{unit_label}} is required to end on {{vacate_date}}, giving you {{notice_days}} days notice as per your lease agreement.\n\nPlease ensure the unit is handed over in its original condition. A move-out inspection will be scheduled closer to the date.\n\nYours faithfully,\nGreen Valley Estate Management',
    variables: ['tenant_name', 'unit_label', 'vacate_date', 'notice_days'],
    active: true,
  },
  {
    id: 'TPL-003',
    name: 'Rent Increase Notice',
    notice_type: 'rent_increase',
    subject: 'NOTICE OF RENT REVIEW — Effective {{effective_date}}',
    body: 'Dear {{tenant_name}},\n\nIn accordance with your tenancy agreement, please be advised that your monthly rent for {{unit_label}} will be revised from KES {{current_rent}} to KES {{new_rent}} effective {{effective_date}}.\n\nThis represents an increase of {{increase_pct}}% in line with prevailing market rates.\n\nYours faithfully,\nGreen Valley Estate Management',
    variables: ['tenant_name', 'unit_label', 'current_rent', 'new_rent', 'effective_date', 'increase_pct'],
    active: true,
  },
]

export const NOTICES: Notice[] = [
  {
    id: 'NTC-001',
    notice_type: 'arrears_demand',
    template_id: 'TPL-001',
    unit_id: 'U-301',
    unit_label: 'Block C – Unit 301',
    person_name: 'David Otieno',
    subject: 'NOTICE OF RENT ARREARS — Block C – Unit 301',
    body: 'Dear David Otieno,\n\nThis notice serves as a formal demand for payment of outstanding rent arrears of KES 45,000 for the period March–April 2024.\n\nPayment is required within 7 days of this notice.',
    status: 'sent',
    created_date: '2024-05-05',
    sent_date: '2024-05-05',
    response_deadline: '2024-05-12',
    created_by: 'Jane Karimi',
    delivery: [
      { method: 'email', delivered_at: '2024-05-05T09:30:00', delivered_to: 'david.otieno@email.com' },
      { method: 'sms', delivered_at: '2024-05-05T09:31:00', delivered_to: '+254 722 334 445' },
    ],
  },
  {
    id: 'NTC-002',
    notice_type: 'breach_notice',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    person_name: 'Samuel Kipchoge',
    subject: 'FORMAL BREACH NOTICE — Noise Violation',
    body: 'Dear Samuel Kipchoge,\n\nThis is a formal notice of breach of House Rules (Noise Curfew). On the evening of 8 June 2024, your unit generated excessive noise past 10 PM, contrary to facility rules.\n\nImmediate compliance is required. Repeat violations will attract fines.',
    status: 'acknowledged',
    created_date: '2024-06-09',
    sent_date: '2024-06-09',
    response_deadline: '2024-06-16',
    acknowledged_date: '2024-06-10',
    created_by: 'Jane Karimi',
    linked_breach_id: 'BRCH-001',
    delivery: [
      { method: 'email', delivered_at: '2024-06-09T10:00:00', delivered_to: 'samuel.kipchoge@email.com', acknowledged_at: '2024-06-10T08:22:00' },
    ],
  },
  {
    id: 'NTC-003',
    notice_type: 'rent_increase',
    template_id: 'TPL-003',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    person_name: 'James Mwangi',
    subject: 'NOTICE OF RENT REVIEW — Effective 1 July 2024',
    body: 'Dear James Mwangi,\n\nYour monthly rent for Block A – Unit 101 will increase from KES 35,000 to KES 38,500 effective 1 July 2024.',
    status: 'sent',
    created_date: '2024-05-31',
    sent_date: '2024-05-31',
    response_deadline: '2024-06-14',
    created_by: 'Jane Karimi',
    delivery: [
      { method: 'email', delivered_at: '2024-05-31T11:00:00', delivered_to: 'james.mwangi@email.com' },
      { method: 'hand_delivered', delivered_at: '2024-05-31T16:30:00', delivered_to: 'James Mwangi (Unit 101 door)' },
    ],
  },
  {
    id: 'NTC-004',
    notice_type: 'maintenance_notice',
    unit_id: 'U-ALL',
    unit_label: 'All Units',
    person_name: 'All Residents',
    subject: 'PLANNED WATER INTERRUPTION — 15 June 2024',
    body: 'Dear Resident,\n\nPlease note that water supply will be interrupted on Saturday 15 June 2024 from 8 AM to 4 PM due to scheduled tank maintenance and pipe flushing.\n\nKindly store adequate water in advance. We apologise for any inconvenience.',
    status: 'sent',
    created_date: '2024-06-10',
    sent_date: '2024-06-10',
    created_by: 'Jane Karimi',
    delivery: [
      { method: 'sms', delivered_at: '2024-06-10T08:00:00', delivered_to: 'All Residents (SMS Broadcast)' },
      { method: 'email', delivered_at: '2024-06-10T08:01:00', delivered_to: 'All Residents (Email Broadcast)' },
    ],
  },
  {
    id: 'NTC-005',
    notice_type: 'notice_to_vacate',
    unit_id: 'U-305',
    unit_label: 'Block C – Unit 305',
    person_name: 'Tenant (U-305)',
    subject: 'NOTICE TO VACATE — Block C – Unit 305',
    body: 'Draft notice pending legal review.',
    status: 'draft',
    created_date: '2024-06-11',
    created_by: 'Jane Karimi',
    linked_breach_id: 'BRCH-003',
    delivery: [],
    notes: 'Pending management approval before sending.',
  },
]
