import type { PersonalStaff } from '@/lib/types'

export const PERSONAL_STAFF: PersonalStaff[] = [
  // ── HH-001 — James Mwangi, Unit 101 ──────────────────────────────────
  {
    id: 'PS-001',
    household_id: 'HH-001',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    employer_person_id: 'P-001',
    employer_name: 'James Mwangi',
    first_name: 'Mary',
    last_name: 'Wanjiku',
    national_id: '34512678',
    phone: '+254 716 100 200',
    role: 'nanny',
    status: 'active',
    access_days: 'weekdays',
    access_hours_start: '07:00',
    access_hours_end: '19:00',
    background_check_done: true,
    background_check_date: '2020-01-18',
    approved_by: 'Facility Manager',
    approved_date: '2020-01-19',
    registered_date: '2020-01-20',
    notes: 'Looks after 2 children. Has emergency contact clearance.',
  },
  {
    id: 'PS-002',
    household_id: 'HH-001',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    employer_person_id: 'P-001',
    employer_name: 'James Mwangi',
    first_name: 'John',
    last_name: 'Kariuki',
    national_id: '22345678',
    phone: '+254 727 200 300',
    role: 'driver',
    status: 'active',
    access_days: 'all',
    access_hours_start: '05:30',
    access_hours_end: '22:00',
    background_check_done: true,
    background_check_date: '2021-06-10',
    approved_by: 'Facility Manager',
    approved_date: '2021-06-11',
    registered_date: '2021-06-12',
  },

  // ── HH-002 — Grace Njoroge, Unit 102 ─────────────────────────────────
  {
    id: 'PS-003',
    household_id: 'HH-002',
    unit_id: 'U-102',
    unit_label: 'Block A – Unit 102',
    employer_person_id: 'P-003',
    employer_name: 'Grace Njoroge',
    first_name: 'Esther',
    last_name: 'Chebet',
    national_id: '38901234',
    phone: '+254 718 300 400',
    role: 'housekeeper',
    status: 'active',
    access_days: 'weekdays',
    access_hours_start: '08:00',
    access_hours_end: '17:00',
    background_check_done: true,
    background_check_date: '2021-03-12',
    approved_by: 'Facility Manager',
    approved_date: '2021-03-14',
    registered_date: '2021-03-15',
  },

  // ── HH-003 — Samuel Kipchoge, Unit 201 ───────────────────────────────
  {
    id: 'PS-004',
    household_id: 'HH-003',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    employer_person_id: 'P-006',
    employer_name: 'Samuel Kipchoge',
    first_name: 'Agnes',
    last_name: 'Auma',
    national_id: '41234567',
    phone: '+254 724 400 500',
    role: 'nanny',
    status: 'active',
    access_days: 'weekdays',
    access_hours_start: '07:30',
    access_hours_end: '18:30',
    background_check_done: false,
    registered_date: '2022-02-01',
    notes: 'Background check pending — follow up with employer',
  },

  // ── HH-005 — David Otieno, Unit 301 ──────────────────────────────────
  {
    id: 'PS-005',
    household_id: 'HH-005',
    unit_id: 'U-301',
    unit_label: 'Block C – Unit 301',
    employer_person_id: 'P-009',
    employer_name: 'David Otieno',
    first_name: 'Lilian',
    last_name: 'Moraa',
    national_id: '44567890',
    phone: '+254 712 500 600',
    role: 'housekeeper',
    status: 'suspended',
    access_days: 'weekdays',
    access_hours_start: '08:00',
    access_hours_end: '17:00',
    background_check_done: true,
    background_check_date: '2024-01-03',
    approved_by: 'Facility Manager',
    approved_date: '2024-01-04',
    registered_date: '2024-01-05',
    notes: 'Access suspended pending incident review.',
  },
]
