import type { HouseRule, BreachRecord } from '@/lib/types'

export const HOUSE_RULES: HouseRule[] = [
  {
    id: 'RULE-001',
    title: 'Noise Curfew',
    description: 'No loud music, parties, or disruptive noise between 10 PM and 7 AM. Noise levels must remain within acceptable limits at all times.',
    category: 'noise',
    severity: 'moderate',
    fine_amount: 5000,
    active: true,
    added_date: '2020-01-01',
  },
  {
    id: 'RULE-002',
    title: 'Designated Parking Only',
    description: 'Residents and guests must park only in their designated bays. Visitor parking is available at the gate — maximum 2 hours without management approval.',
    category: 'parking',
    severity: 'minor',
    fine_amount: 2000,
    active: true,
    added_date: '2020-01-01',
  },
  {
    id: 'RULE-003',
    title: 'Waste Disposal',
    description: 'All waste must be bagged and placed in the designated bins by 7 AM on collection days. Bulk items must be disposed of via management.',
    category: 'waste',
    severity: 'minor',
    fine_amount: 1500,
    active: true,
    added_date: '2020-01-01',
  },
  {
    id: 'RULE-004',
    title: 'No Unauthorised Pets',
    description: 'Pets require written approval from management. Approved pets must be leashed in common areas. No dangerous breeds permitted.',
    category: 'pets',
    severity: 'moderate',
    fine_amount: 10000,
    active: true,
    added_date: '2020-06-01',
  },
  {
    id: 'RULE-005',
    title: 'No Subletting Without Approval',
    description: 'Subletting any portion of a unit, including through short-stay platforms, requires written management approval and an addendum to the lease.',
    category: 'subletting',
    severity: 'serious',
    fine_amount: 25000,
    active: true,
    added_date: '2021-01-01',
  },
  {
    id: 'RULE-006',
    title: 'Common Area Conduct',
    description: 'Common areas including the gym, pool, and garden are available 6 AM–10 PM. No food or drinks in the gym. Children under 12 must be supervised at the pool.',
    category: 'common_areas',
    severity: 'minor',
    fine_amount: 2000,
    active: true,
    added_date: '2020-01-01',
  },
  {
    id: 'RULE-007',
    title: 'Rent Payment Deadline',
    description: 'Rent is due on the 1st of each month. A penalty of 2% per week applies after a 5-day grace period.',
    category: 'payments',
    severity: 'serious',
    active: true,
    added_date: '2020-01-01',
  },
]

export const BREACH_RECORDS: BreachRecord[] = [
  {
    id: 'BRCH-001',
    rule_id: 'RULE-001',
    rule_title: 'Noise Curfew',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    person_name: 'Samuel Kipchoge',
    incident_date: '2024-06-08',
    reported_date: '2024-06-09',
    reported_by: 'Neighbour — U-202',
    severity: 'moderate',
    description: 'Loud music and party activity reported past midnight on Saturday. Multiple neighbours complained.',
    status: 'warned',
    warning_issued_date: '2024-06-09',
    warning_issued_by: 'Jane Karimi',
    notes: 'First offence. Verbal and written warning issued.',
  },
  {
    id: 'BRCH-002',
    rule_id: 'RULE-002',
    rule_title: 'Designated Parking Only',
    unit_id: 'U-102',
    unit_label: 'Block A – Unit 102',
    person_name: 'Grace Njoroge',
    incident_date: '2024-06-10',
    reported_date: '2024-06-10',
    reported_by: 'Gate Officer John',
    severity: 'minor',
    description: 'Visitor vehicle parked in reserved bay P-007 belonging to Block B owner. Vehicle blocking access.',
    status: 'resolved',
    warning_issued_date: '2024-06-10',
    warning_issued_by: 'Gate Officer John',
    resolved_date: '2024-06-10',
    resolution_notes: 'Tenant reminded of guest parking procedure. Vehicle moved within 20 mins.',
  },
  {
    id: 'BRCH-003',
    rule_id: 'RULE-005',
    rule_title: 'No Subletting Without Approval',
    unit_id: 'U-305',
    unit_label: 'Block C – Unit 305',
    person_name: 'Unknown (Tenant)',
    incident_date: '2024-05-20',
    reported_date: '2024-05-22',
    reported_by: 'Security Observation',
    severity: 'serious',
    description: 'Unit observed on Airbnb listing without management approval. Multiple short-stay guests noted in access logs.',
    status: 'fined',
    warning_issued_date: '2024-05-23',
    warning_issued_by: 'Jane Karimi',
    fine_amount: 25000,
    notes: 'Tenant denies intent. Lease review meeting scheduled.',
  },
  {
    id: 'BRCH-004',
    rule_id: 'RULE-004',
    rule_title: 'No Unauthorised Pets',
    unit_id: 'U-103',
    unit_label: 'Block A – Unit 103',
    person_name: 'Unoccupied (Previous Tenant)',
    incident_date: '2024-04-25',
    reported_date: '2024-04-28',
    reported_by: 'Move-Out Inspection',
    severity: 'moderate',
    description: 'Evidence of pets (cat) in unit during move-out inspection. Scratched skirting boards and dander found.',
    status: 'resolved',
    fine_amount: 10000,
    resolved_date: '2024-05-10',
    resolution_notes: 'Deducted from deposit. Unit professionally cleaned.',
  },
]
