import type { Unit } from '@/lib/types'

export const UNITS: Unit[] = [
  { id:'U-101', block:'A', floor:1, number:'101', size_sqm:65, bedrooms:2, bathrooms:1, use_type:'residential', status:'occupied',    monthly_rate:45000, current_occupant:'James Mwangi',  lease_end:'2025-12-31', owners:[{person_id:'P-01', ownership_type:'individual', name:'Grace Njeri',   share_percent:100, is_resident:false, is_primary:true}] },
  { id:'U-102', block:'A', floor:1, number:'102', size_sqm:65, bedrooms:2, bathrooms:1, use_type:'residential', status:'occupied',    monthly_rate:45000, current_occupant:'Sarah Otieno',  lease_end:'2025-09-30', owners:[{person_id:'P-02', ownership_type:'individual', name:'David Kamau',  share_percent:100, is_resident:false, is_primary:true}] },
  { id:'U-103', block:'A', floor:1, number:'103', size_sqm:55, bedrooms:1, bathrooms:1, use_type:'vacant',      status:'vacant',      monthly_rate:38000, owners:[{person_id:'P-03', ownership_type:'individual', name:'Mary Wanjiku',  share_percent:100, is_resident:false, is_primary:true}] },
  { id:'U-201', block:'A', floor:2, number:'201', size_sqm:80, bedrooms:3, bathrooms:2, use_type:'residential', status:'occupied',    monthly_rate:60000, current_occupant:'Peter Ochieng', lease_end:'2026-03-31', owners:[{person_id:'P-04', ownership_type:'individual', name:'Ann Mutua',   share_percent:60, is_resident:false, is_primary:true},{person_id:'P-05', ownership_type:'individual', name:'John Mutua', share_percent:40, is_resident:false, is_primary:false}] },
  { id:'U-202', block:'A', floor:2, number:'202', size_sqm:80, bedrooms:3, bathrooms:2, use_type:'bnb',         status:'occupied',    monthly_rate:8000,  current_occupant:'BnB Guest',     owners:[{person_id:'P-06', ownership_type:'individual', name:'Lucy Kariuki', share_percent:100, is_resident:true, is_primary:true}] },
  { id:'U-203', block:'A', floor:2, number:'203', size_sqm:75, bedrooms:3, bathrooms:2, use_type:'office',      status:'occupied',    monthly_rate:70000, current_occupant:'TechCorp Ltd',  lease_end:'2026-06-30', owners:[{person_id:'P-07', ownership_type:'individual', name:'Sam Njoroge',  share_percent:100, is_resident:false, is_primary:true}] },
  { id:'U-301', block:'A', floor:3, number:'301', size_sqm:90, bedrooms:3, bathrooms:2, use_type:'residential', status:'maintenance', monthly_rate:65000, owners:[{person_id:'P-01', ownership_type:'individual', name:'Grace Njeri', share_percent:100, is_resident:false, is_primary:true}] },
  { id:'U-302', block:'A', floor:3, number:'302', size_sqm:90, bedrooms:3, bathrooms:2, use_type:'residential', status:'occupied',    monthly_rate:65000, current_occupant:'Rose Akinyi',   lease_end:'2025-08-31', owners:[{person_id:'P-08', ownership_type:'individual', name:'Tom Oduya',    share_percent:100, is_resident:true, is_primary:true}] },
  { id:'S-01',  block:'S', floor:0, number:'S01', size_sqm:40, bedrooms:0, bathrooms:1, use_type:'commercial',  status:'occupied',    monthly_rate:80000, current_occupant:'Mini Market',   lease_end:'2027-01-31', owners:[{person_id:'P-09', ownership_type:'individual', name:'Jane Muthoni', share_percent:100, is_resident:false, is_primary:true}] },
  { id:'S-02',  block:'S', floor:0, number:'S02', size_sqm:35, bedrooms:0, bathrooms:1, use_type:'commercial',  status:'vacant',      monthly_rate:75000, owners:[{person_id:'P-09', ownership_type:'individual', name:'Jane Muthoni', share_percent:100, is_resident:false, is_primary:true}] },
]
