import type { Vehicle } from '@/lib/types'

export const VEHICLES: Vehicle[] = [
  // ── Block A – Unit 101 (James Mwangi, owner-resident) ──────────────────
  {
    id: 'VEH-001',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    household_id: 'HH-001',
    registered_to_person_id: 'P-001',
    registered_to_name: 'James Mwangi',
    make: 'Toyota', model: 'Prado', year: 2021, color: 'Silver',
    plate_number: 'KDG 123A',
    sticker_number: 'GV-0101',
    vehicle_type: 'suv',
    status: 'active',
    registered_date: '2020-01-20',
    insurance_expiry: '2025-01-31',
  },
  {
    id: 'VEH-002',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    household_id: 'HH-001',
    registered_to_person_id: 'P-001',
    registered_to_name: 'James Mwangi',
    make: 'Honda', model: 'Fit', year: 2019, color: 'White',
    plate_number: 'KBZ 456C',
    sticker_number: 'GV-0102',
    vehicle_type: 'car',
    status: 'active',
    registered_date: '2020-01-20',
    insurance_expiry: '2025-03-15',
    notes: 'Used by spouse',
  },

  // ── Block A – Unit 102 (Grace Njoroge, tenant) ─────────────────────────
  {
    id: 'VEH-003',
    unit_id: 'U-102',
    unit_label: 'Block A – Unit 102',
    household_id: 'HH-002',
    registered_to_person_id: 'P-003',
    registered_to_name: 'Grace Njoroge',
    make: 'Mazda', model: 'CX-5', year: 2020, color: 'Black',
    plate_number: 'KDD 789F',
    sticker_number: 'GV-0201',
    vehicle_type: 'suv',
    status: 'active',
    registered_date: '2021-03-15',
    insurance_expiry: '2025-06-30',
  },

  // ── Block B – Unit 201 (Samuel Kipchoge, tenant) ───────────────────────
  {
    id: 'VEH-004',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    household_id: 'HH-003',
    registered_to_person_id: 'P-006',
    registered_to_name: 'Samuel Kipchoge',
    make: 'Nissan', model: 'X-Trail', year: 2018, color: 'Grey',
    plate_number: 'KCX 321B',
    sticker_number: 'GV-0301',
    vehicle_type: 'suv',
    status: 'active',
    registered_date: '2022-01-10',
    insurance_expiry: '2024-12-31',
    notes: 'Insurance expired — renewal pending',
  },
  {
    id: 'VEH-005',
    unit_id: 'U-201',
    unit_label: 'Block B – Unit 201',
    household_id: 'HH-003',
    registered_to_person_id: 'P-006',
    registered_to_name: 'Samuel Kipchoge',
    make: 'Bajaj', model: 'Boxer', year: 2022, color: 'Red',
    plate_number: 'KMCK 001S',
    sticker_number: 'GV-0302',
    vehicle_type: 'motorcycle',
    status: 'active',
    registered_date: '2022-06-01',
  },

  // ── Block B – Unit 205 (Beatrice Achieng, tenant) ─────────────────────
  {
    id: 'VEH-006',
    unit_id: 'U-205',
    unit_label: 'Block B – Unit 205',
    household_id: 'HH-004',
    registered_to_person_id: 'P-008',
    registered_to_name: 'Beatrice Achieng',
    make: 'Subaru', model: 'Forester', year: 2017, color: 'Blue',
    plate_number: 'KBP 654D',
    sticker_number: 'GV-0401',
    vehicle_type: 'suv',
    status: 'active',
    registered_date: '2023-03-20',
    insurance_expiry: '2025-04-15',
  },

  // ── Block C – Unit 301 (David Otieno, tenant) ─────────────────────────
  {
    id: 'VEH-007',
    unit_id: 'U-301',
    unit_label: 'Block C – Unit 301',
    household_id: 'HH-005',
    registered_to_person_id: 'P-009',
    registered_to_name: 'David Otieno',
    make: 'Toyota', model: 'Corolla', year: 2016, color: 'White',
    plate_number: 'KCM 777G',
    sticker_number: 'GV-0501',
    vehicle_type: 'car',
    status: 'suspended',
    registered_date: '2024-01-05',
    notes: 'Suspended — overstayed visitor vehicle converted to resident',
  },
]
