import type { Visitor, VisitorPass, GateLog } from '@/lib/types'

export const VISITORS: Visitor[] = [
  {
    id: 'VIS-001',
    full_name: 'Kevin Omondi',
    phone: '+254 700 321 654',
    national_id: '36221100',
    host_unit_id: 'U-101',
    host_unit_label: 'Block A – Unit 101',
    host_name: 'James Mwangi',
    purpose: 'personal_visit',
    vehicle_plate: 'KBZ 234A',
    expected_date: '2024-06-13',
    time_in: '10:30',
    status: 'signed_in',
    signed_in_by: 'Gate Officer John',
    is_pre_registered: true,
  },
  {
    id: 'VIS-002',
    full_name: 'DHL Courier — Joseph Mwenda',
    phone: '+254 722 111 333',
    host_unit_id: 'U-205',
    host_unit_label: 'Block B – Unit 205',
    host_name: 'Beatrice Achieng',
    purpose: 'delivery',
    expected_date: '2024-06-13',
    time_in: '09:15',
    time_out: '09:22',
    status: 'signed_out',
    signed_in_by: 'Gate Officer John',
    signed_out_by: 'Gate Officer John',
  },
  {
    id: 'VIS-003',
    full_name: 'Plumber — Ahmed Suleiman',
    phone: '+254 733 876 543',
    national_id: '29887766',
    host_unit_id: 'U-302',
    host_unit_label: 'Block C – Unit 302',
    host_name: 'David Otieno',
    purpose: 'contractor',
    vehicle_plate: 'KCJ 890B',
    expected_date: '2024-06-13',
    status: 'expected',
    is_pre_registered: true,
    notes: 'Maintenance work order WO-015. Accompanied by site foreman.',
  },
  {
    id: 'VIS-004',
    full_name: 'Unnamed Walk-in',
    phone: '+254 799 000 111',
    host_unit_id: 'U-103',
    host_unit_label: 'Block A – Unit 103',
    host_name: 'Unoccupied',
    purpose: 'viewing',
    expected_date: '2024-06-12',
    status: 'denied',
    denied_reason: 'Unit unoccupied. No authorisation from management on record.',
  },
  {
    id: 'VIS-005',
    full_name: 'Sarah Waweru',
    phone: '+254 711 555 777',
    national_id: '37654321',
    host_unit_id: 'U-201',
    host_unit_label: 'Block B – Unit 201',
    host_name: 'Samuel Kipchoge',
    purpose: 'personal_visit',
    expected_date: '2024-06-12',
    time_in: '18:00',
    time_out: '22:45',
    status: 'signed_out',
    signed_in_by: 'Gate Officer Mary',
    signed_out_by: 'Gate Officer Mary',
    is_pre_registered: false,
  },
]

export const VISITOR_PASSES: VisitorPass[] = [
  {
    id: 'PASS-001',
    visitor_name: 'Housekeeper — Mary Njoki',
    host_unit_id: 'U-101',
    host_unit_label: 'Block A – Unit 101',
    pass_type: 'recurring',
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    used_count: 24,
    access_hours_start: '07:00',
    access_hours_end: '17:00',
    issued_by: 'James Mwangi',
    issued_at: '2024-01-01T09:00:00',
    active: true,
    notes: 'Regular housekeeper — Mon & Thu access',
  },
  {
    id: 'PASS-002',
    visitor_name: 'IT Contractor — NairobiNet',
    host_unit_id: 'U-205',
    host_unit_label: 'Block B – Unit 205',
    pass_type: 'contractor',
    valid_from: '2024-06-10',
    valid_until: '2024-06-20',
    max_uses: 5,
    used_count: 1,
    vehicle_plates: ['KDA 456C'],
    issued_by: 'Jane Karimi',
    issued_at: '2024-06-10T08:00:00',
    active: true,
    notes: 'Internet cabling upgrade work',
  },
]

export const GATE_LOGS: GateLog[] = [
  {
    id: 'GLOG-001',
    timestamp: '2024-06-13T10:30:00',
    direction: 'entry',
    person_name: 'Kevin Omondi',
    person_type: 'visitor',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    vehicle_plate: 'KBZ 234A',
    visitor_id: 'VIS-001',
    verified_by: 'Gate Officer John',
    method: 'manual',
  },
  {
    id: 'GLOG-002',
    timestamp: '2024-06-13T09:15:00',
    direction: 'entry',
    person_name: 'Joseph Mwenda (DHL)',
    person_type: 'visitor',
    unit_id: 'U-205',
    unit_label: 'Block B – Unit 205',
    visitor_id: 'VIS-002',
    verified_by: 'Gate Officer John',
    method: 'manual',
  },
  {
    id: 'GLOG-003',
    timestamp: '2024-06-13T09:22:00',
    direction: 'exit',
    person_name: 'Joseph Mwenda (DHL)',
    person_type: 'visitor',
    visitor_id: 'VIS-002',
    verified_by: 'Gate Officer John',
    method: 'manual',
  },
  {
    id: 'GLOG-004',
    timestamp: '2024-06-13T08:55:00',
    direction: 'entry',
    person_name: 'James Mwangi',
    person_type: 'resident',
    unit_id: 'U-101',
    unit_label: 'Block A – Unit 101',
    vehicle_plate: 'KCA 112A',
    method: 'card',
  },
  {
    id: 'GLOG-005',
    timestamp: '2024-06-13T07:45:00',
    direction: 'entry',
    person_name: 'Grace Njoroge',
    person_type: 'resident',
    unit_id: 'U-102',
    unit_label: 'Block A – Unit 102',
    method: 'card',
  },
  {
    id: 'GLOG-006',
    timestamp: '2024-06-12T22:45:00',
    direction: 'exit',
    person_name: 'Sarah Waweru',
    person_type: 'visitor',
    visitor_id: 'VIS-005',
    verified_by: 'Gate Officer Mary',
    method: 'manual',
  },
]
